timeout: 30m
options:
  logging: GCS_ONLY
logsBucket: ${_BUILD_LOG_BUCKET}
steps:
        - id: 'build'
          name: 'google/cloud-sdk:543.0.0'
          entrypoint: 'sh'
          args: ['scripts/build-python.sh']

        - id: 'configuration'
          name: 'google/cloud-sdk:543.0.0'
          entrypoint: 'make'
          args: ['-f', 'scripts/configure-terraform.mk']
          env:
          - CONFIG_BUCKET=${_CONFIG_BUCKET}

        - id: 'terraform'
          name: 'hashicorp/terraform:1.13'
          entrypoint: 'sh'
          args: ['scripts/run-terraform.sh']
